alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: iflavio.dev
  type: PRIMARY
  zone: iflavio.dev
name: portfolio-react
region: nyc
services:
- build_command: yarn build
  environment_slug: node-js
  git:
    branch: main
    repo_clone_url: https://github.com/flavioespinoza/sample-react.git
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-s
  name: sample-react
  routes:
  - path: /